<?php

namespace AssossiationBundle\Repository;

/**
 * AssossiationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssossiationRepository extends \Doctrine\ORM\EntityRepository
{
}
