reclamation_reclamation:
    resource: "@ReclamationBundle/Controller/ReclamationController.php"
    type:     annotation

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation


assossiation_assossiation:
    resource: "@AssossiationBundle/Controller/AssossiationController.php"
    type:     annotation

assossiation:
    resource: "@AssossiationBundle/Resources/config/routing.yml"
    prefix:   /assossiation

temp:
    resource: "@TempBundle/Resources/config/routing.yml"
    prefix:   /temp

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
